BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = ../lib
ARDUINO_LIBS = Wire SHT1x DS1307RTC Time TimeAlarms LiquidCrystal_I2C ArduinoThread TimerOne EEPROM
MAKEFILE_DIR = ../Arduino-Makefile

#ARDUINO_DIR = /home/nico/Documents/arduino-1.5.6-r2/arduino
ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = $(MAKEFILE_DIR)
AVR_TOOLS_DIR = /usr

include $(MAKEFILE_DIR)/Arduino.mk
