BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = ../lib
ARDUINO_LIBS = SHT1x
MAKEFILE_DIR = ../Arduino-Makefile

ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = $(MAKEFILE_DIR)
AVR_TOOLS_DIR = /usr

include $(MAKEFILE_DIR)/Arduino.mk
